import {defineConfig,type Plugin} from 'vite';
import {readFile} from 'node:fs/promises';

const KEY_PATH=process.env.OPENAI_KEY_FILE||'/home/john/Documents/oai-key';
const OPENAI='https://api.openai.com/v1';
let activeProvider='OPENAI';
const languageName=(tag:string)=>new Intl.DisplayNames(['en'],{type:'language'}).of(tag.split('-')[0])||tag;
const readBody=(req:any)=>new Promise<any>((resolve,reject)=>{let raw='';req.on('data',(x:Buffer)=>raw+=x);req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch(e){reject(e)}});req.on('error',reject)});
const send=(res:any,code:number,value:any)=>{res.statusCode=code;res.setHeader('content-type','application/json');res.end(JSON.stringify(value))};
async function key(){return (process.env.OPENAI_API_KEY||(await readFile(KEY_PATH,'utf8'))).trim()}
async function realtimeToken(tag:string){const source=(tag||'en-US').split('-')[0];const response=await fetch(`${OPENAI}/realtime/client_secrets`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${await key()}`},body:JSON.stringify({expires_after:{anchor:'created_at',seconds:600},session:{type:'transcription',audio:{input:{format:{type:'audio/pcm',rate:24000},transcription:{model:'gpt-4o-mini-transcribe',language:source},noise_reduction:{type:'far_field'},turn_detection:{type:'server_vad',threshold:.45,prefix_padding_ms:300,silence_duration_ms:250}}}}})});const json:any=await response.json();if(!response.ok)throw new Error(json.error?.message||`Realtime token ${response.status}`);return {value:json.value,expires_at:json.expires_at}}
function prompt(body:any){const lang=languageName(body.language||'en-US'),count=Math.max(1,Math.min(8,Number(body.count||8))),history=[...(body.turns||[]).slice(-16).map((x:any)=>`${x.speaker}: ${x.text}`),...(body.preview?[`other (live partial): ${body.preview}`]:[])].join('\n')||'No completed turns yet.',active=(body.activeBranches||[]).map((x:any,i:number)=>`${i+1}. ${x.english}`).join('\n'),style=body.style==='S'?'strategic, empathetic, trust-building':body.style==='C'?'argumentative and contrarian: challenge assumptions and offer sharp, evidence-seeking, non-hostile counterpoints':'playful, warm, lightly flirty when welcome';return `You are a real-time conversation copilot. Selected language: ${lang}. Style: ${style}. The selected language is authoritative. Predict the next one or two likely turns and produce specific, organic replies useful now and on those paths.\nConversation:\n${history}\nCurrent queue to compete against:\n${active}\nReturn ONLY JSON with context and exactly ${count} branches shaped {english,native,phonetic,relevance}. relevance is 0-100 for immediate fit plus usefulness on the predictable next turn. ${count===8?'Use the inquisitive/declarative risk 1-4 matrix.':'Return the strongest varied alternatives.'} Risk 4 is maximally socially bold but never coercive, deceptive, illegal, harassing, or boundary-violating. Each field is one complete thought, no newline, max 72 characters. If ${lang} is English, copy english into native and phonetic. Otherwise all three text fields are required; phonetic pronounces native, NEVER the English meaning. Capitalize stressed phonetic syllables.`}
const cardSchema=(count:number)=>({type:'object',additionalProperties:false,required:['context','branches'],properties:{context:{type:'string'},branches:{type:'array',minItems:count,maxItems:count,items:{type:'object',additionalProperties:false,required:['english','native','phonetic','relevance'],properties:{english:{type:'string'},native:{type:'string'},phonetic:{type:'string'},relevance:{type:'integer',minimum:0,maximum:100}}}}}});
async function suggest(body:any){const count=Math.max(1,Math.min(8,Number(body.count||8))),response=await fetch(`${OPENAI}/responses`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${await key()}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.2',input:prompt(body),store:false,max_output_tokens:count<=4?800:1600,text:{format:{type:'json_schema',name:'conversation_branches',strict:true,schema:cardSchema(count)}}})});const json:any=await response.json();if(!response.ok)throw new Error(json.error?.message||`OpenAI ${response.status}`);const text=json.output_text??json.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text;if(!text)throw new Error(`OpenAI returned no text (${json.status||'unknown'})`);const parsed=JSON.parse(text);if(!Array.isArray(parsed.branches)||parsed.branches.length!==count)throw new Error(`Provider did not return ${count} branches`);return parsed}
async function transcribe(audio:string,tag:string){const bytes=Buffer.from(audio,'base64'),form=new FormData(),source=(tag||'en-US').split('-')[0],translate=source!=='en';form.append('file',new Blob([bytes],{type:'audio/wav'}),'turn.wav');form.append('model',translate?'whisper-1':(process.env.OPENAI_TRANSCRIBE_MODEL||'gpt-4o-mini-transcribe'));if(!translate)form.append('language',source);const response=await fetch(`${OPENAI}/audio/${translate?'translations':'transcriptions'}`,{method:'POST',headers:{authorization:`Bearer ${await key()}`},body:form});const json:any=await response.json();if(!response.ok)throw new Error(json.error?.message||`Transcription ${response.status}`);return json.text?.trim()||''}
function localApi():Plugin{return{name:'g2-local-api',configureServer(server){server.middlewares.use('/api/config',async(_req,res)=>send(res,200,{provider:activeProvider}));server.middlewares.use('/api/provider',async(req,res)=>{try{activeProvider=(await readBody(req)).provider||'OPENAI';send(res,200,{provider:activeProvider})}catch(e:any){send(res,500,{error:e.message})}});server.middlewares.use('/api/realtime-token',async(req,res)=>{try{const body=await readBody(req);send(res,200,await realtimeToken(body.language))}catch(e:any){send(res,500,{error:e.message})}});server.middlewares.use('/api/transcribe',async(req,res)=>{try{const body=await readBody(req),transcript=await transcribe(body.audio,body.language);send(res,200,transcript?{transcript,speaker:'unknown',noSpeech:false}:{noSpeech:true})}catch(e:any){send(res,500,{error:e.message})}});server.middlewares.use('/api/turn',async(req,res)=>{try{if(activeProvider!=='OPENAI')throw new Error('Install/start the Android companion bridge to use this provider without Ubuntu');const body=await readBody(req),transcript=await transcribe(body.audio,body.language);if(!transcript){send(res,200,{noSpeech:true});return}body.turns=[...(body.turns||[]),{speaker:'unknown',text:transcript}];send(res,200,{transcript,speaker:'unknown',provider:activeProvider,...(await suggest(body))})}catch(e:any){send(res,500,{error:e.message})}});server.middlewares.use('/api/suggest',async(req,res)=>{try{if(activeProvider!=='OPENAI')throw new Error('Install/start the Android companion bridge to use this provider without Ubuntu');send(res,200,{provider:activeProvider,...(await suggest(await readBody(req)))})}catch(e:any){send(res,500,{error:e.message})}})}}}
export default defineConfig({plugins:[localApi()],server:{host:'0.0.0.0',port:5173,strictPort:true,headers:{'Access-Control-Allow-Origin':'*'}},build:{outDir:'dist',emptyOutDir:true}});
