import {defineConfig,type Plugin} from 'vite';
import {readFile} from 'node:fs/promises';

const KEY_PATH=process.env.OPENAI_KEY_FILE||'/home/john/Documents/oai-key';
const OPENAI='https://api.openai.com/v1';
const languageName=(tag:string)=>new Intl.DisplayNames(['en'],{type:'language'}).of(tag.split('-')[0])||tag;
const readBody=(req:any)=>new Promise<any>((resolve,reject)=>{let raw='';req.on('data',(x:Buffer)=>raw+=x);req.on('end',()=>{try{resolve(JSON.parse(raw||'{}'))}catch(e){reject(e)}});req.on('error',reject)});
const send=(res:any,code:number,value:any)=>{res.statusCode=code;res.setHeader('content-type','application/json');res.end(JSON.stringify(value))};
async function key(){return (process.env.OPENAI_API_KEY||(await readFile(KEY_PATH,'utf8'))).trim()}
function prompt(body:any){const lang=languageName(body.language||'en-US'),history=(body.turns||[]).slice(-16).map((x:any)=>`${x.speaker}: ${x.text}`).join('\n')||'No completed turns yet.';return `You are a real-time conversation copilot. Selected language: ${lang}. Style: ${body.style==='S'?'strategic, empathetic, trust-building':'playful, warm, lightly flirty when welcome'}. The selected language is authoritative.\nConversation:\n${history}\nReturn ONLY JSON: {"context":"clean English translation of the latest turn, or Ready if none","branches":[{"english":"English meaning","native":"actual ${lang} reply","phonetic":"American-English-readable pronunciation of native"}]}. Return exactly 8 branches in order: inquisitive risk 1, declarative risk 1, inquisitive risk 2, declarative risk 2, inquisitive risk 3, declarative risk 3, inquisitive risk 4, declarative risk 4. Risk 4 is maximally socially bold but never coercive, deceptive, illegal, harassing, or boundary-violating. Each field is one complete thought, no newline, max 72 characters. If ${lang} is English, native and phonetic are empty. Otherwise all three fields are required; phonetic pronounces native, NEVER the English meaning. Capitalize stressed phonetic syllables.`}
const cardSchema={type:'object',additionalProperties:false,required:['context','branches'],properties:{context:{type:'string'},branches:{type:'array',minItems:8,maxItems:8,items:{type:'object',additionalProperties:false,required:['english','native','phonetic'],properties:{english:{type:'string'},native:{type:'string'},phonetic:{type:'string'}}}}}};
async function suggest(body:any){const response=await fetch(`${OPENAI}/responses`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${await key()}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.2',input:prompt(body),store:false,max_output_tokens:1600,text:{format:{type:'json_schema',name:'conversation_branches',strict:true,schema:cardSchema}}})});const json:any=await response.json();if(!response.ok)throw new Error(json.error?.message||`OpenAI ${response.status}`);const text=json.output_text??json.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text;if(!text)throw new Error(`OpenAI returned no text (${json.status||'unknown'})`);const parsed=JSON.parse(text);if(!Array.isArray(parsed.branches)||parsed.branches.length!==8)throw new Error('Provider did not return eight branches');return parsed}
async function transcribe(audio:string,tag:string){const bytes=Buffer.from(audio,'base64'),form=new FormData();form.append('file',new Blob([bytes],{type:'audio/wav'}),'turn.wav');form.append('model',process.env.OPENAI_TRANSCRIBE_MODEL||'gpt-4o-mini-transcribe');form.append('language',(tag||'en-US').split('-')[0]);const response=await fetch(`${OPENAI}/audio/transcriptions`,{method:'POST',headers:{authorization:`Bearer ${await key()}`},body:form});const json:any=await response.json();if(!response.ok)throw new Error(json.error?.message||`Transcription ${response.status}`);return json.text?.trim()||''}
function localApi():Plugin{return{name:'g2-local-api',configureServer(server){server.middlewares.use('/api/turn',async(req,res)=>{try{const body=await readBody(req),transcript=await transcribe(body.audio,body.language);if(!transcript)throw new Error('No speech detected');body.turns=[...(body.turns||[]),{speaker:'unknown',text:transcript}];send(res,200,{transcript,speaker:'unknown',...(await suggest(body))})}catch(e:any){send(res,500,{error:e.message})}});server.middlewares.use('/api/suggest',async(req,res)=>{try{send(res,200,await suggest(await readBody(req)))}catch(e:any){send(res,500,{error:e.message})}})}}}
export default defineConfig({plugins:[localApi()],server:{host:'0.0.0.0',port:5173,strictPort:true,headers:{'Access-Control-Allow-Origin':'*'}},build:{outDir:'dist',emptyOutDir:true}});
