import './style.css'
import {AudioInputSource,EventSourceType,OsEventTypeList,StartUpPageCreateResult,waitForEvenAppBridge} from '@evenrealities/even_hub_sdk'

type Branch={english:string;native:string;phonetic:string};type Turn={speaker:string;text:string};
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const status=$<HTMLParagraphElement>('status'),log=$<HTMLPreElement>('log'),language=$<HTMLSelectElement>('language'),style=$<HTMLSelectElement>('style'),native=$<HTMLInputElement>('native');
let bridge:any,recording=false,focus=0,viewport=0,context='Ready',branches:Branch[]=[],turns:Turn[]=[],pcm:number[]=[],speaking=false,lastVoice=0,rendered='',busy=false;
const saved=JSON.parse(localStorage.getItem('g2copilot.settings')||'{}');language.value=saved.language||'en-US';style.value=saved.style||'P';native.checked=!!saved.native;
function save(){localStorage.setItem('g2copilot.settings',JSON.stringify({language:language.value,style:style.value,native:native.checked}));render()}
language.onchange=save;style.onchange=save;native.onchange=save;
function write(message:string){log.textContent=`${new Date().toLocaleTimeString()} ${message}\n${log.textContent}`.slice(0,7000)}
function shown(b:Branch){return language.value.startsWith('en')?b.english:`${b.english}\n${native.checked?b.native:b.phonetic}`}
function content(){if(!branches.length)return `${context}\n\nListening for a complete turn…`;const a=branches[viewport],b=branches[viewport+1];return `${context}\n\n${focus===viewport?'>':'•'} ${shown(a)}${b?`\n\n${focus===viewport+1?'>':'•'} ${shown(b)}`:''}`}
async function render(){const next=content();if(next===rendered||!bridge)return;rendered=next;await bridge.textContainerUpgrade({containerID:1,containerName:'copilot',content:next})}
function move(delta:number){if(!branches.length)return;focus=Math.max(0,Math.min(branches.length-1,focus+delta));if(focus<viewport)viewport=focus;if(focus>viewport+1)viewport=focus-1;render()}
function wavBase64(bytes:number[]){const n=bytes.length,buf=new ArrayBuffer(44+n),v=new DataView(buf);const s=(o:number,x:string)=>[...x].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));s(0,'RIFF');v.setUint32(4,36+n,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,n,true);new Uint8Array(buf,44).set(bytes);let binary='';for(const x of new Uint8Array(buf))binary+=String.fromCharCode(x);return btoa(binary)}
function energy(bytes:Uint8Array){let sum=0,n=0;for(let i=0;i+1<bytes.length;i+=2){const x=(bytes[i]|bytes[i+1]<<8)<<16>>16;sum+=x*x;n++}return n?Math.sqrt(sum/n):0}
async function finishTurn(){if(pcm.length<16000||busy){pcm=[];return}const audio=wavBase64(pcm);pcm=[];busy=true;status.textContent='Transcribing and generating…';try{const r=await fetch('/api/turn',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({audio,language:language.value,style:style.value,turns})});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);turns=[...turns,{speaker:data.speaker||'unknown',text:data.transcript}].slice(-20);context=data.context;merge(data.branches,false);write(`Heard: ${data.transcript}`);status.textContent='Listening'}catch(e:any){write(`ERROR ${e.message}`);status.textContent=e.message}finally{busy=false}}
function merge(next:Branch[],force:boolean){if(force||!branches.length)branches=next.slice(0,8);else branches=next.slice(0,8).map((x,i)=>Math.abs(i-focus)<=1?(branches[i]||x):x);focus=Math.min(focus,branches.length-1);render()}
async function refreshAll(){if(busy)return;busy=true;status.textContent='Refreshing all branches…';try{const r=await fetch('/api/suggest',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({language:language.value,style:style.value,turns})});const data=await r.json();if(!r.ok)throw new Error(data.error);context=data.context||context;merge(data.branches,true);write('All eight branches refreshed');status.textContent=recording?'Listening':'Ready'}catch(e:any){write(`ERROR ${e.message}`);status.textContent=e.message}finally{busy=false}}
async function toggleMic(){recording=!recording;const ok=await bridge.audioControl(recording,AudioInputSource.Glasses);if(!ok){recording=false;throw new Error('G2 microphone could not be opened')}status.textContent=recording?'Listening':'Microphone stopped';$('mic').textContent=recording?'Stop G2 microphone':'Start G2 microphone'}
$('mic').onclick=()=>toggleMic().catch((e:any)=>{status.textContent=e.message;write(`ERROR ${e.message}`)});$('refresh').onclick=refreshAll;

async function start(){bridge=await waitForEvenAppBridge();const created=await bridge.createStartUpPageContainer({containerTotalNum:1,textObject:[{xPosition:0,yPosition:0,width:576,height:288,paddingLength:10,containerID:1,containerName:'copilot',content:content(),isEventCapture:1}],menuObject:{menuItems:[{itemName:'Refresh branches',itemID:1},{itemName:'Start / stop mic',itemID:2}]}});if(created!==StartUpPageCreateResult.success)throw new Error(`Glasses page failed: ${created}`);bridge.onEvenHubEvent((event:any)=>{const audio=event.audioEvent;if(audio&&recording){const bytes:Uint8Array=audio.audioPcm;const e=energy(bytes),now=Date.now();if(e>650){speaking=true;lastVoice=now}if(speaking)pcm.push(...bytes);if(speaking&&now-lastVoice>700){speaking=false;finishTurn()}if(pcm.length>384000){speaking=false;finishTurn()}}
const ev=event.sysEvent||event.textEvent||event.listEvent;const type=ev?.eventType;if(type===OsEventTypeList.SCROLL_TOP_EVENT)move(-1);if(type===OsEventTypeList.SCROLL_BOTTOM_EVENT)move(1);if(type===OsEventTypeList.CLICK_EVENT&&(ev.eventSource===undefined||ev.eventSource===EventSourceType.TOUCH_EVENT_FROM_RING))refreshAll();if(type===OsEventTypeList.DOUBLE_CLICK_EVENT)bridge.shutDownPageContainer(0);if(event.menuItemClickEvent?.itemID===1)refreshAll();if(event.menuItemClickEvent?.itemID===2)toggleMic();});await toggleMic();await refreshAll();write('Even G2 bridge connected')}
start().catch((e:any)=>{status.textContent=e.message;write(`STARTUP ERROR ${e.stack||e.message}`)})
