import './style.css'
import {AudioInputSource,OsEventTypeList,StartUpPageCreateResult,waitForEvenAppBridge} from '@evenrealities/even_hub_sdk'

type Branch={english:string;native:string;phonetic:string};type Turn={speaker:string;text:string};
const BUILD='0.1.1-20260915';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const status=$<HTMLParagraphElement>('status'),log=$<HTMLPreElement>('log'),provider=$<HTMLSelectElement>('provider'),language=$<HTMLSelectElement>('language'),style=$<HTMLSelectElement>('style'),native=$<HTMLInputElement>('native');
let bridge:any,recording=false,focus=0,viewport=0,context='Ready',branches:Branch[]=[],turns:Turn[]=[],pcm:number[]=[],preRoll:number[]=[],speaking=false,lastVoice=0,rendered='';
let transcribing=false,suggesting=false,suggestionQueued=false,forceQueued=false,generation=0;const audioQueue:string[]=[];
let apiBase='';async function apiFetch(path:string,init?:RequestInit){const candidates=apiBase?[apiBase]:['http://127.0.0.1:8787',`${location.origin}/api`];let last:any;for(const base of candidates){try{const response=await fetch(`${base}${path}`,init);apiBase=base;return response}catch(e){last=e}}throw last||new Error('Provider bridge unreachable')}
const saved=JSON.parse(localStorage.getItem('g2copilot.settings')||'{}');language.value=saved.language||'en-US';style.value=saved.style||'P';native.checked=!!saved.native;
function save(){localStorage.setItem('g2copilot.settings',JSON.stringify({language:language.value,style:style.value,native:native.checked}))}
language.onchange=()=>{save();generation++;branches=[];focus=viewport=0;context='Listening…';rendered='';render();requestSuggestions(true)};
style.onchange=()=>{save();requestSuggestions(true)};native.onchange=()=>{save();rendered='';render()};
provider.onchange=async()=>{try{const r=await apiFetch('/provider',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider:provider.value})});const data=await r.json();if(!r.ok)throw new Error(data.error);write(`Backend: ${provider.options[provider.selectedIndex].text}`);requestSuggestions(true)}catch(e:any){status.textContent=e.message;write(`PROVIDER ERROR ${e.message}`)}};
function write(message:string){log.textContent=`${new Date().toLocaleTimeString()} ${message}\n${log.textContent}`.slice(0,7000)}
function shown(b:Branch){if(language.value.startsWith('en'))return b.english;const second=native.checked?b.native:b.phonetic;return second?`${b.english}\n${second}`:b.english}
function visibleCount(){return language.value.startsWith('en')?4:2}function branchContent(){if(!branches.length)return 'Listening for a complete turn…';return branches.slice(viewport,viewport+visibleCount()).map((b,i)=>`${focus===viewport+i?'>':'•'} ${shown(b)}`).join('\n')}
async function render(){const next=`${context}\u0000${branchContent()}`;if(next===rendered||!bridge)return;rendered=next;await Promise.all([bridge.textContainerUpgrade({containerID:1,containerName:'context',content:context}),bridge.textContainerUpgrade({containerID:4,containerName:'branches',content:branchContent()})])}
function move(delta:number){if(!branches.length)return;focus=Math.max(0,Math.min(branches.length-1,focus+delta));const count=visibleCount();if(focus<viewport)viewport=focus;if(focus>=viewport+count)viewport=focus-count+1;render()}
function wavBase64(bytes:number[]){const n=bytes.length,buf=new ArrayBuffer(44+n),v=new DataView(buf);const s=(o:number,x:string)=>[...x].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));s(0,'RIFF');v.setUint32(4,36+n,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,n,true);new Uint8Array(buf,44).set(bytes);let binary='';for(const x of new Uint8Array(buf))binary+=String.fromCharCode(x);return btoa(binary)}
function energy(bytes:Uint8Array){let sum=0,n=0;for(let i=0;i+1<bytes.length;i+=2){const x=(bytes[i]|bytes[i+1]<<8)<<16>>16;sum+=x*x;n++}return n?Math.sqrt(sum/n):0}
function finishTurn(){if(pcm.length<9600){pcm=[];return}audioQueue.push(wavBase64(pcm));if(audioQueue.length>3)audioQueue.shift();pcm=[];drainAudio()}
async function drainAudio(){if(transcribing)return;transcribing=true;while(audioQueue.length){const audio=audioQueue.shift()!;status.textContent=language.value.startsWith('en')?'Transcribing…':'Translating speech…';try{const r=await apiFetch('/transcribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({audio,language:language.value})});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);if(data.noSpeech||!data.transcript){status.textContent=recording?'Listening':'Ready';continue}turns=[...turns,{speaker:data.speaker||'unknown',text:data.transcript}].slice(-20);context=data.transcript;render();write(`${language.value.startsWith('en')?'Heard':'English'}: ${data.transcript}`);requestSuggestions(false)}catch(e:any){write(`TRANSCRIPTION ERROR ${e.message}`);status.textContent=recording?'Listening':'Ready'}}transcribing=false;if(!suggesting)status.textContent=recording?'Listening':'Ready'}
function validBranches(value:any):value is Branch[]{return Array.isArray(value)&&value.length>0&&value.every((b:any)=>b&&typeof b.english==='string'&&typeof b.native==='string'&&typeof b.phonetic==='string')}
function merge(next:Branch[],force:boolean){if(!validBranches(next)){write('BRANCH ERROR provider returned no usable branch array');return}const incoming=next.slice(0,8);if(force||!branches.length)branches=incoming;else branches=incoming.map((x,i)=>Math.abs(i-focus)<=1?(branches[i]||x):x);focus=Math.max(0,Math.min(focus,branches.length-1));render()}
async function requestSuggestions(force:boolean){generation++;forceQueued=forceQueued||force;if(suggesting){suggestionQueued=true;return}suggesting=true;do{suggestionQueued=false;const thisGeneration=generation;const replaceAll=forceQueued;forceQueued=false;status.textContent='Generating branches…';try{const r=await apiFetch('/suggest',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({language:language.value,style:style.value,turns})});const data=await r.json();if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);if(!validBranches(data.branches))throw new Error('Provider response did not contain branches');if(thisGeneration===generation){context=typeof data.context==='string'&&data.context?data.context:context;merge(data.branches,replaceAll);write(`All eight branches refreshed · ${data.provider||provider.value}`)}}catch(e:any){write(`BRANCH ERROR ${e.message}`)}}while(suggestionQueued);suggesting=false;status.textContent=recording?'Listening':'Ready'}
function refreshAll(){requestSuggestions(true)}
async function toggleMic(){recording=!recording;const ok=await bridge.audioControl(recording,AudioInputSource.Glasses);if(!ok){recording=false;throw new Error('G2 microphone could not be opened')}status.textContent=recording?'Listening':'Microphone stopped';$('mic').textContent=recording?'Stop G2 microphone':'Start G2 microphone'}
$('mic').onclick=()=>toggleMic().catch((e:any)=>{status.textContent=e.message;write(`ERROR ${e.message}`)});$('refresh').onclick=refreshAll;

async function start(){write(`BUILD ${BUILD}`);bridge=await waitForEvenAppBridge();try{const r=await apiFetch('/config'),data=await r.json();if(r.ok&&data.provider)provider.value=data.provider;write(`Bridge: ${apiBase}`)}catch(e){write('Start the companion provider bridge for standalone mode')};const page={containerTotalNum:4,textObject:[{xPosition:0,yPosition:0,width:576,height:78,paddingLength:1,containerID:1,containerName:'context',content:context,isEventCapture:0},{xPosition:0,yPosition:79,width:576,height:209,paddingLength:1,containerID:4,containerName:'branches',content:branchContent(),isEventCapture:1}],imageObject:[{xPosition:0,yPosition:78,width:288,height:20,containerID:2,containerName:'line-left'},{xPosition:288,yPosition:78,width:288,height:20,containerID:3,containerName:'line-right'}],menuObject:{menuItems:[{itemName:'Refresh branches',itemID:1},{itemName:'Start / stop mic',itemID:2}]}};const created=await bridge.createStartUpPageContainer(page);if(created!==StartUpPageCreateResult.success){const rebuilt=await bridge.rebuildPageContainer(page);if(!rebuilt)throw new Error(`Glasses page failed: ${created}`)}const line=new Array(288*20).fill(0);for(let x=0;x<288;x++)line[x]=255;await Promise.all([bridge.updateImageRawData({containerID:2,containerName:'line-left',imageData:line}),bridge.updateImageRawData({containerID:3,containerName:'line-right',imageData:line})]);bridge.onEvenHubEvent((event:any)=>{const audio=event.audioEvent;if(audio&&recording){const bytes:Uint8Array=audio.audioPcm;const e=energy(bytes),now=Date.now();if(!speaking){preRoll.push(...bytes);if(preRoll.length>9600)preRoll.splice(0,preRoll.length-9600);if(e>650){speaking=true;lastVoice=now;pcm=preRoll;preRoll=[]}}else{pcm.push(...bytes);if(e>650)lastVoice=now;if(now-lastVoice>250){speaking=false;finishTurn()}if(pcm.length>384000){speaking=false;finishTurn()}}}
const ev=[event.sysEvent,event.textEvent,event.listEvent].find((candidate:any)=>candidate?.eventType!==undefined);const type=OsEventTypeList.fromJson(ev?.eventType);if(type===OsEventTypeList.SCROLL_TOP_EVENT)move(-1);if(type===OsEventTypeList.SCROLL_BOTTOM_EVENT)move(1);if(type===OsEventTypeList.CLICK_EVENT){write(`R1 press · source ${ev?.eventSource??'captured'}`);refreshAll()}if(type===OsEventTypeList.DOUBLE_CLICK_EVENT)bridge.shutDownPageContainer(0);if(event.menuItemClickEvent?.itemID===1)refreshAll();if(event.menuItemClickEvent?.itemID===2)toggleMic();});await toggleMic();refreshAll();write('Even G2 bridge connected')}
start().catch((e:any)=>{status.textContent=e.message;write(`STARTUP ERROR ${e.stack||e.message}`)})
